### ISSUE TITLE
Support debian with ppa install

### ISSUE THREAD

**Issue by beraboris** [saltstack-formulas/node-formula#11]
Installing from ppa is currently done through nodesource.

According to their [readme file](https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions), nodesource supports installing on debian.

This formula should support installing node on debian through nodesource.

**Comment by gravyboat** [comment]
This was already done: https://github.com/saltstack-formulas/node-formula/commit/8f419676ec078f2e445ca14e0829e0edca629fa0

**Comment by gravyboat** [comment]
If I'm not understanding what it is you're looking for please let me know, otherwise let's close this out.

**Comment by beraboris** [comment]
The formula doesn't install from the ppa on debian because of this line:
https://github.com/saltstack-formulas/node-formula/blob/master/node/pkg.sls#L3

The condition explicitly checks for Ubuntu.

**Comment by gravyboat** [comment]
@beraboris Ahh good point, if you want to tackle this feel free to do so. @johnklehm Is there anything with your changes or the node PPA that would let us simply add `or 'debian'` to the grains os check? My familiarity with node is pretty much 0.

**Comment by beraboris** [comment]
Sadly, I'm just starting out with salt I don't think I know enough not to break something.

**Comment by johnklehm** [comment]
I can take a shot at making it work on debian next week if no one beats me to it. Not familiar enough with debian to say if it woukd just work without testing.

**Comment by beraboris** [comment]
I can give it a quick test once it's done.
