### ISSUE TITLE
Don't use --silent flag

### ISSUE THREAD

**Issue by alexhayes** [saltstack-formulas/node-formula#12]
Using the `--silent` flag for bootstrapping with `npm install` might be useful to hide verbose output when successful, however when an issue occurs (for instance, permissions to `~/.npm`) it's rather annoying as there is no output, simply just an error code - which is rather unhelpful.

Is there another reason I'm unaware of that requires the setting of the `--silent` flag?

**Comment by puneetk** [comment]
I agree it's worth improving, do you want to send a pull and make that parameter configurable via a pillar

**Comment by alexhayes** [comment]
I don't know why I raised this here... it's actually in salt's core.

I've created PR [25091](https://github.com/saltstack/salt/pull/25091) over there.
