### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by h3x3d** [saltstack-formulas/node-formula#29]
## When installing from ppa

```
      ID: nodejs.ppa
Function: pkgrepo.managed
    Name: deb https://deb.nodesource.com/node_5.x trusty main
  Result: False
 Comment: You may not use both "keyid"/"keyserver" and "key_url" argument.
 Started: 10:05:01.887191
Duration: 2.185 ms
 Changes:
```

**Comment by gravyboat** [comment]
Either https://github.com/saltstack-formulas/node-formula/blob/master/node/pkg.sls#L15 needs to be dropped, or lines 14 and 16 need to be dropped. If you want to run a quick test with line 15 removed (and then 14 and 16 if that doesn't work) to confirm it works then make a PR dropping it that would be great.

**Comment by ek9** [comment]
This does not seem to cause problems any more. Suggesting to close. Otherwise let me know, I can submit a PR.
