### ISSUE TITLE
Centos/Redhat

### ISSUE THREAD

**Issue by JulioECastro** [saltstack-formulas/node-formula#30]
I can't use it for my Centos and Redhat instances.
I think to change pkg install (then a will l use a condition)... but some packages are missing.
What do you recommend?

Ensure required packages are present:
  pkg.installed:
    - names:
      - openssl-devel #libssl-dev
      - git
      - pkgconfig #pkg-config
      - build-essential #no
      - curl
      - gcc
      - gcc-c++ # g++
      - checkinstall #no

**Comment by gravyboat** [comment]
What packages are missing? Can we not add them into the `map.jinja` and address it that way?

**Comment by JulioECastro** [comment]
My first try was install from source... node version 0.10.30 :( 
Some packages has different names for Centos7. For example... libssl-dev is openssl-devel.
Build-essential doesn't exist in yum, but I include make and make and automake
I get Checkinstall from external repo. this is my current code but Im follow testing.

Ensure required packages are present:
  pkg.installed:
    - names:
      - openssl-devel #libssl-dev
      - git
      - pkgconfig #pkg-config
      # - build-essential #no
      - curl
      - gcc
      - gcc-c++ # g++
      # - checkinstall #no
       - make
       - automake

Package checkinstall missing:
  pkg.installed:
    - sources:
      - checkinstall: salt://cache/checkinstall/checkinstall-1.6.2-20.4.x86_64.rpm

**Comment by gravyboat** [comment]
If you would like feel free to prep a PR that adds the missing/incorrect names to the map.jinja for CentOS and then references it correctly for the package installation.
