### ISSUE TITLE
Use newer `deb` PPA (still on `node_6.x`)

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/node-formula#44]
https://github.com/saltstack-formulas/node-formula/blob/03b12c2ed8ff0c3d310bd8d1adb64a87f84cfccb/node/pkg.sls#L11

Still using `node_6.x` when `10` (and even `11`) are available:

* https://deb.nodesource.com/node_10.x/dists/
* https://deb.nodesource.com/node_11.x/dists/

Is there a specific reason for this?

**Comment by aboe76** [comment]
I don't know about the specifics, but having the version variable in pillar data should make it more flexible, I think you added the pillar examples in the last pr. #45

**Comment by myii** [comment]
@aboe76 Thanks for reminding me about this issue.  Looking at the blame, that commit (9e492ff) is from years back, so I think I'll update this as well, to go alongside #45.  Is that OK with you?
